--DO NOT RUN ALL AT ONCE. WILL NOT WORK UNLESS EACH ONE IS STEPPED IN INDIVIDUALLY.
--I DID NOT KNOW IF THIS WAS OKAY TO DO SINCE NOTHING WAS SPECIFIED IN THE BOOK.

CREATE DATABASE DEMOGRAPHICS;

USE DEMOGRAPHICS;

CREATE TABLE POPULATION_STATS (
COUNTRY_NAME varchar(25),
POPULATION varchar(25) NOT NULL,
LANGUAGE VARCHAR(25) NOT NULL,
PRIMARY KEY (COUNTRY_NAME));


INSERT INTO POPULATION_STATS VALUES('Belgium','10404000','Dutch');
INSERT INTO POPULATION_STATS VALUES('Netherlands','16645000','Dutch');
INSERT INTO POPULATION_STATS VALUES('England','60944000','English');
INSERT INTO POPULATION_STATS VALUES('France','62100000','French');
INSERT INTO POPULATION_STATS VALUES('Austria','8206000','German');
INSERT INTO POPULATION_STATS VALUES('Germany','82370000','German');
INSERT INTO POPULATION_STATS VALUES('Liechenstein','34500','German');
INSERT INTO POPULATION_STATS VALUES('Italy','58145000','Italian');
INSERT INTO POPULATION_STATS VALUES('Portugal','10677000','Portuguese');
INSERT INTO POPULATION_STATS VALUES('Spain','40491000','Spanish');

SELECT * FROM POPULATION_STATS;

--A LIST OF ALL RECORDS SORTED BY COUNTRY NAME
SELECT * FROM POPULATION_STATS
ORDER BY 'COUNTRY_NAME';


--THE COUNTRY WITH THE HIGHEST POPULATION
SELECT * FROM POPULATION_STATS
ORDER BY 'POPULATION' DESC;


--THE COUNTRY WITH THE LOWEST POPULATION
SELECT * FROM POPULATION_STATS
ORDER BY 'POPULATION' ASC;

USE DEMOGRAPHICS;
--COUNTRIES THAT SHARE A COMMON LANGUAGE, SUCH AS FRENCH
SELECT * FROM POPULATION_STATS
ORDER BY 'LANGUAGE';
